### ISSUE TITLE
Several crashes on Android reported by Crashlytics

### ISSUE THREAD

**Issue by masterbd** [capacitor-community/firebase-analytics#39] opened 2020-10-16 12:35 UTC
**Describe the bug**
I'm getting many crashes reported by Firebase Crashlytics caused by some messaging dependency (com.google.firebase.iid.zzbe and com.getcapacitor.CapacitorFirebaseMessagingService) . 

**To Reproduce**
I was not able to reproduce it consistently. The error happened more frequent in production.

**Expected behavior**
While I can handle some crashes here and there due to huge ecosystem Android has, I've had a very small number Crash-Free users on Android, 64%.

**Screenshots**
[Link to gallery](https://imgur.com/a/XZrldB4)
[SS 1](https://i.imgur.com/4OZg27e.png)
[SS 2](https://i.imgur.com/enCTcbm.png)
[SS 3](https://i.imgur.com/nsJzZea.png)
[SS 4](https://i.imgur.com/yxTJc4P.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
Android devices. No pattern has been found in terms of OS Versions

**Additional context**
I'm also using some other capacitor-community plugins that may have some impact (@capacitor-community/*admob*, @capacitor-community/*firebase-analytics*, @capacitor-community/*firebase-crashlytics*, @capacitor-community/*firebase-remote-config*, @capacitor-community/*media*). I'll attach the complete plugin list below:
```bash
ionic info
```
```bash
Ionic:

   Ionic CLI                     : 6.12.0 
   Ionic Framework               : @ionic/angular 5.3.4
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.2.1) : 1.0.0

System:

   NodeJS : v14.6.0
   npm    : 6.14.8
   OS     : macOS Catalina
```

package.json
```json
"dependencies": {
    "@angular/common": "^9.1.12",
    "@angular/core": "^9.1.12",
    "@angular/forms": "^9.1.12",
    "@angular/platform-browser": "^9.1.12",
    "@angular/platform-browser-dynamic": "^9.1.12",
    "@angular/router": "^9.1.12",
    "@capacitor-community/admob": "^1.2.0-0",
    "@capacitor-community/firebase-analytics": "^0.2.0",
    "@capacitor-community/firebase-crashlytics": "^0.3.0",
    "@capacitor-community/firebase-remote-config": "^0.1.3",
    "@capacitor-community/media": "^1.0.1",
    "@capacitor/android": "^2.4.0",
    "@capacitor/core": "^2.4.0",
    "@capacitor/ios": "^2.4.0",
    "@ionic-native/core": "^5.28.0",
    "@ionic-super-tabs/angular": "^7.0.8",
    "@ionic/angular": "^5.3.2",
    "@ionic/storage": "^2.3.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "cordova-sqlite-storage": "^5.0.1",
    "ngx-countup": "^7.3.3",
    "rxjs": "~6.5.1",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.901.12",
    "@angular/cli": "^9.1.12",
    "@angular/compiler": "^9.1.12",
    "@angular/compiler-cli": "^9.1.12",
    "@angular/language-service": "^9.1.12",
    "@capacitor/cli": "^2.4.0",
    "@ionic/angular-toolkit": "^2.3.3",
    "@types/jasmine": "^3.5.14",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.12.54",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^5.2.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "ts-node": "~8.3.0",
    "tslint": "^6.1.3",
    "typescript": "~3.8.3"
  }
```

**Comment by mattsteve** [comment] 2020-10-20 18:37
I can reproduce this locally, just by installing `@capacitor-community/firebase-analytics@latest` in my project and running the android app, it will crash the first time I launch the app. I have to uninstall the app and install it on the phone again to see it crash again, but it consistently crashes the first time after install.

Error looks something like this:

```
java.lang.InstantiationError: com.google.firebase.iid.zzbe
     at com.google.firebase.messaging.zzc.onBind
```

**Comment by DURK** [comment] 2020-10-29 10:48
**UPDATE**
Updating to `firebaseMessagingVersion =  '20.2.3'` in `variables.gradle` fixed this issue for me! 👍  For me, the crash consistently occurred whenever a Push Notification was received.

@mattsteve same issue here, I'm seeing a big spike in similar crash reports since releasing our app with this Capacitor-plugin. 
Could it be that this plugin is using an old version of firebase-analytics? Maybe updating [this line ](https://github.com/capacitor-community/firebase-analytics/blob/master/android/build.gradle#L55) to `com.google.firebase:firebase-analytics:18.0.0` will fix it?

I just noticed that the actual error comes not from **firebase-analytics**, but from **firebase-messaging**:
`java.lang.InstantiationError: at com.google.firebase.messaging.zzc.onBind(com.google.firebase:firebase-messaging@@20.1.2:11)`

Maybe it's the combination of the 2 package versions that is the problem? Maybe this will solve it?
https://github.com/capacitor-community/firebase-analytics/issues/18#issuecomment-652601035

**Comment by brownoxford** [comment] 2021-04-06 20:32
Closing, as this seems to be resolved with an update to `firebaseMessagingVersion`. If you are still having this issue, please open a new issue and reference this one.

**Closed as completed by brownoxford** 2021-04-06 20:32 UTC
